### ISSUE TITLE
Icons pack miss Title

### ISSUE THREAD

**Issue by maksii** [tetiana-nizdropa/drawio-icons#6]
The current libraries do not declare an icon title, which limits the ability to find them through built-in tools

![image](https://user-images.githubusercontent.com/1761348/213683323-65ff501d-4e7a-419f-9951-1ff3f32724b7.png)
![image](https://user-images.githubusercontent.com/29313142/213686807-23d3e304-0b39-4b2b-8f04-df748acd9593.png)
![image](https://user-images.githubusercontent.com/1761348/213683630-621c8645-6ba4-421d-96f8-c21936077747.png)

Should be:
![image](https://user-images.githubusercontent.com/1761348/213683366-887ab9a7-c523-4c3f-befc-e4846951433c.png)
![image](https://user-images.githubusercontent.com/1761348/213683452-7cee4515-009c-4db4-89d9-1907bdd33890.png)

To fix an issue - add `"title":"ICON_NAME"`

**Comment by tetiana-nizdropa** [comment]
Resolved with #8 pr
